### PR TITLE
Recreate Pipfile.lock

### PR DESCRIPTION
**Pull request by samuelallan72**
Dependabot has been complaining for a while, and we haven't updated this in a long time.

Will need to test to check everything still works.

### CODE REVIEW

**Comment by lostways** [comment]
Works great for me. I'm not using docker, but tried with pipenv directly....


➜  sncli-fork git:(bump-deps) pipenv install --dev                                                                                                                                                                              Installing dependencies from Pipfile.lock (e4a7b1)…                                                                                                                                                                               🎃   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 38/38 — 00:00:27                                                                                                                                                                        To activate this project's virtualenv, run the following:                                                                                                                                                                        $ pipenv shell                                                                                                                                                                                                                 ➜  sncli-fork git:(bump-deps) pipenv shell                                                                                                                                                                                      Spawning environment shell (/usr/bin/zsh). Use 'exit' to leave.                                                                                                                                                                 . /home/ubuntu/.local/share/virtualenvs/sncli-fork-_bhrWyJs/bin/activate                                                                                                                                                        ➜  sncli-fork git:(bump-deps) . /home/ubuntu/.local/share/virtualenvs/sncli-fork-_bhrWyJs/bin/activate                                                                                                                          (sncli-fork-_bhrWyJs) ➜  sncli-fork git:(bump-deps) ./sncli --help                                                                                                                                                                                                                                                                                                                                                                                              Usage:                                                                                                                                                                                                                           sncli [OPTIONS] [COMMAND] [COMMAND_ARGS]                                                                                                                                                                                                                                                                                                                                                                                                                        OPTIONS:                                                                                                                                                                                                                         -h, --help                  - usage help                                                                                                                                                                                        -v, --verbose               - verbose output
.......                             

I also tested editing and creating a note via the gui.

**Comment by swalladge** [comment]
@pataquets @lostways thanks for sharing!  I'm a little hesitant to merge the updates, since that first crash.  The traceback looks rather like a regression in urwid itself (originating in drawing the widgets).  Or maybe a `Text` node that isn't properly inited?

```
AttributeError: 'Text' object has no attribute '_cache_translation'
```

Maybe the bug is triggered by i18n config?  What language is your system using @pataquets ?

**Comment by pataquets** [comment]
@swalladge: I've done a bit more diagnosing following your question. Although I've not found the exact cause of the crash (which I can't reliably reproduce always), my guess is that it might be something locale-related, indeed.
My lang-related environment vars.
```
LANG=ca_ES.UTF-8
LANGUAGE=ca:ca@valencia:es:en
LC_ADDRESS=ca_ES.UTF-8
LC_IDENTIFICATION=ca_ES.UTF-8
LC_MEASUREMENT=ca_ES.UTF-8
LC_MONETARY=ca_ES.UTF-8
LC_NAME=ca_ES.UTF-8
LC_NUMERIC=ca_ES.UTF-8
LC_PAPER=ca_ES.UTF-8
LC_TELEPHONE=ca_ES.UTF-8
LC_TIME=ca_ES.UTF-8
```
I've also discovered that the Docker image has faulty support for non-English locales (eg. accented chars) and I'm working in a Dockerfile fix to allow baking some specific locale at container build time via an `ARG` parameter, defaulting to `en_US.UTF-8` to keep current behavior. As soon as the PR is done and merged, if you rebase this PR to the latest `HEAD`, I want to put this PR's image to normal use again and test.

As far as my error report concerns, I think it can be dismissed due to missing locale inside my Docker image, if someone with non-EN_US locale can confirm it's working (/cc @lostways). I can't dismiss that based on my evidence alone. So far, I've got some crashes when saving a note with accented chars.

**Comment by pataquets** [comment]
@swalladge: now that #125 is in, mind you rebasing this on latest `HEAD` as discussed above?

**Pull request closed without merging**
